server:
  port: 8311
spring:
  application:
    name: spring-cloud-frontend
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-agent-address: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
